apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nebulastream.fullname" . }}-secrets
  labels: {{- include "nebulastream.labels" . | nindent 4 }}
type: Opaque
stringData:
  CLOUDFLARE_API_TOKEN: {{ .Values.secrets.cloudflareApiToken | quote }}
  CLOUDFLARE_ACCOUNT_ID: {{ .Values.secrets.cloudflareAccountId | quote }}
