apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: control-plane
  namespace: nebulastream
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: control-plane
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
